name: Release

on:
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Meta
        env:
          REF_NAME: ${{github.ref_name}}
        run: |
          echo "version=$REF_NAME" >> "$GITHUB_OUTPUT"
          echo "tags=ghcr.io/kubecon-2023-na-argocd-helm-support/payments:$REF_NAME" >> "$GITHUB_OUTPUT"
        id: meta
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Publish Helm Chart
        env:
          VERSION: ${{ steps.meta.outputs.version }}
        run: |
          sed -i "s/tag: latest/tag: $VERSION/g" charts/payments/values.yaml
          helm package --version $VERSION --app-version $VERSION charts/payments -d dist
          git checkout gh-pages
          mv dist/* .
          helm repo index . --url https://kubecon-2023-na-argocd-helm-support.github.io/payments
          git add . && git commit -m "Publish $VERSION" && git push origin gh-pages
